languaje: swift
osx_image: xcode13.1
branches:
 only:
   - master

before_install:
 - gem install fastlane --no-ri --no-rdoc --no-document
install: true
script:
 - fastlane scan --scheme TAU --device "iPod touch" 
